version: "3.8"
services: 
  main:
    container_name: app
    build: './apache/'
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/
    networks:
      - backend

  mysql:
    container_name: db
    platform: linux/x86_64
    image: mysql:8.0.26
    networks:
      - backend
    volumes:
      - 'native-api-server-mysql:/var/lib/mysql'

  redis:
    container_name: cache
    platform: linux/x86_64
    image: redis:latest
    networks:
      - backend


networks:
  backend:
volumes:
    native-api-server-mysql:
        driver: local
